server.servlet.context-path=/api/v1
server.port=8082
spring.application.name=Spring 3 and Keycloak

spring.datasource.url=jdbc:postgresql://192.168.2.58:5432/pfm_base
spring.datasource.username=george
spring.datasource.password=george
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

logging.level.com.example=debug
logging.level.org.springframework.security=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://local.keycloak.com/realms/private-financial-manager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://local.keycloak.com/realms/private-financial-manager/protocol/openid-connect/certs